### ISSUE TITLE
g++4 command not found: while trying to install therubyracer -v '0.9.8'

### ISSUE THREAD

**Issue by krish203** [svent/jsdetox#16]
OS: RHEL 6
gcc version 4.4.7 20120313 (Red Hat) (GCC)

We will need to create a sym link for gcc4: 

ln -s /usr/bin/g++ /usr/bin/g++4 

for compilation of v8_value.cpp to succeed 

Just FYI

**Comment by svent** [comment]
Thanks for putting the info here - I will close this now.
