### ISSUE TITLE
Bundle install fails on i18n in OS X 10.8.5

### ISSUE THREAD

**Issue by ajnachakra** [svent/jsdetox#17]
```
~/jsdetox$ bundle install 
```

Fails with:

```
Gem::InstallError: i18n requires Ruby version >= 1.9.3.
An error occurred while installing i18n (0.7.0), and Bundler cannot continue.
Make sure that `gem install i18n -v '0.7.0'` succeeds before bundling.
Bundler::InstallError: An error occurred while installing i18n (0.7.0), and Bundler cannot continue.
Make sure that `gem install i18n -v '0.7.0'` succeeds before bundling.
```

Manually running 'gem install i18n -v 0.7.0' does not resolve this (even though it has no errors).

Any suggestions?

Context:
- OS X 10.8.5
- Python 2.7.2
- clang --version Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn) Target: x86_64-apple-darwin12.5.0 Thread model: posix
- ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin12.0]

**Comment by svent** [comment]
You say that you use ruby 2.2.0, but the error message suggests that bundler tries to use a ruby version < 1.9.3. Do you use a ruby version manager (rvm, chruby, etc.)?
I am not sure what exactly leads to this error, and unfortunately I do not have access to a test system with that setup.
