### ISSUE TITLE
Analysis button gets stucked at "loading..."

### ISSUE THREAD

**Issue by nmaxcom** [svent/jsdetox#24]
The analysis part of the tool seems to do nothing. Well, the rest of it doesn't respond either.

First I installed jsdetox in my OSX and when I saw that I thought it was the OS, even though there were no errors. So I installed it in my Debian and the same.

I don't see errors anywhere:

![image](https://cloud.githubusercontent.com/assets/8936090/23601497/04b1126a-024c-11e7-9458-5df2dfd7ca55.png)

I've been stripping down the code to easier and easier bits just to try. I even tried the sample on your website: `var x = 10 * 3 + 100 - 70 / 10;` but this is all i get:

![image](https://cloud.githubusercontent.com/assets/8936090/23601547/62787596-024c-11e7-9c32-a65a02543af7.png)

**Comment by nmaxcom** [comment]
It was weird the disparity between what I saw in Chrome and back in the server so I dug a little more. Using a _requester_ app I found I could get the backend to do the analysis so it was something in the frontend.

Long story short, one ad blocking extension in my browser was blocking my requests. I filtered the site and It's working now! 😁

**Comment by svent** [comment]
Thanks for analyzing this and documenting it here, this might help other people having similar issues.
Great to hear it works now for you!

**Comment by nmaxcom** [comment]
Thank you for developing the app. It's a shame that it hasn't been updated/improved in so many years, though. There are plenty of nice features and improvements that could be added. If I knew ruby I'd help out (or if it had been written in js or c/c++ 😜)
